### ISSUE TITLE
Dependency restriction for python-magic and olefile

### ISSUE THREAD

**Issue by DJRHails** [hatching/sflock#51]
Currently sflock requires `olefile==0.43` and `python-magic==0.4.12`. These were the latest versions at the time of commit, but are now outdated.

The requirement can be changed to `olefile>=0.43` and `python-magic>=0.4.12, <0.5` without issue. This would allow `oletools` to be included at a later version alongside sflock.

**Comment by doomedraven** [comment]
see PRs, there is py3 port WIP
